
services:
  pgvector-service:
    image: ankane/pgvector
    container_name: pgvector-service
    environment:
      POSTGRES_DB: embd
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./pgvector-db:/var/lib/postgresql/data
      - ./sql-scripts:/docker-entrypoint-initdb.d
